package tech.zaisys.archivum.api.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import tech.zaisys.archivum.api.enums.SourceType;

import java.util.UUID;

/**
 * Request to create a new source before scanning.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateSourceRequest {

    /**
     * Unique source ID (generated by scanner)
     */
    private UUID id;

    /**
     * User-provided logical name
     */
    private String name;

    /**
     * Type of source
     */
    private SourceType type;

    /**
     * Root path being scanned
     */
    private String rootPath;

    /**
     * Physical identification metadata
     */
    private PhysicalId physicalId;

    /**
     * Parent source ID (if this is a child source)
     */
    private UUID parentSourceId;

    /**
     * Whether this source is postponed
     */
    private Boolean postponed;

    /**
     * User notes
     */
    private String notes;
}
