package tech.zaisys.archivum.api.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import tech.zaisys.archivum.api.enums.FileStatus;

import java.time.Instant;
import java.util.UUID;

/**
 * Represents a scanned file with metadata and hash.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class FileDto {

    /**
     * Unique file ID (generated by scanner)
     */
    private UUID id;

    /**
     * Source ID this file belongs to
     */
    private UUID sourceId;

    /**
     * Relative path within the source
     */
    private String path;

    /**
     * File name
     */
    private String name;

    /**
     * File extension (without dot)
     */
    private String extension;

    /**
     * File size in bytes
     */
    private Long size;

    /**
     * SHA-256 hash
     */
    private String sha256;

    /**
     * File modification time
     */
    private Instant modifiedAt;

    /**
     * File creation time (if available)
     */
    private Instant createdAt;

    /**
     * File access time (if available)
     */
    private Instant accessedAt;

    /**
     * MIME type (if detected)
     */
    private String mimeType;

    /**
     * EXIF metadata (for images)
     */
    private ExifMetadata exif;

    /**
     * File status
     */
    private FileStatus status;

    /**
     * Whether this file is a duplicate
     */
    private Boolean isDuplicate;

    /**
     * If duplicate, the ID of the original file
     */
    private UUID originalFileId;

    /**
     * When this record was scanned
     */
    private Instant scannedAt;
}
